# Generated by Django 2.2.2 on 2019-06-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinfo',
            name='goods',
            field=models.ForeignKey(on_delete=False, to='df_goods.GoodsInfo'),
        ),
        migrations.AlterField(
            model_name='cartinfo',
            name='user',
            field=models.ForeignKey(on_delete=False, to='df_user.UserInfo'),
        ),
    ]
