# Generated by Django 2.2.2 on 2019-06-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0003_auto_20180221_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='goods',
            field=models.ForeignKey(on_delete=False, to='df_goods.GoodsInfo'),
        ),
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='order',
            field=models.ForeignKey(on_delete=False, to='df_order.OrderInfo'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=False, to='df_user.UserInfo'),
        ),
    ]
